### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by ghost** [fxmorin/memoryLeakFix#180]
I haven't tried changing the fabic mod json or anything, I'm sure it would work find but it would still be nice ig.

**Comment by KennyDevT** [comment]
a dependency (Spruce UI) is not has not been updated since 1.20.4. so they would have to switch to Obsidian UI.

**Comment by GamerGuy95953** [comment]
> I haven't tried changing the fabic mod json or anything, I'm sure it would work find but it would still be nice ig.

If you don't want to wait, it should still work as for me it's detecting memory leaks from some of my mods.

**Comment by KennyDevT** [comment]
> > I haven't tried changing the fabic mod json or anything, I'm sure it would work find but it would still be nice ig.
> 
> If you don't want to wait, it should still work as for me it's detecting memory leaks from some of my mods.

For me it crashes every time a load a world so i gotta wait.

**Comment by ajaxnotmeta** [comment]
does 1.21 still leaking though?

**Comment by itsarian** [comment]
any updates?

**Comment by arsel-5lvxa7b1** [comment]
@KennyDevT @GamerGuy95953 @mharbb @itsarian @ajaxnotmeta

Owner is not working on it anymore

https://github.com/FxMorin/MemoryLeakFix/issues/177#issuecomment-2168541518

**Comment by Soabac** [comment]
oh well

**Comment by XandarNull** [comment]
I would love it if the devs updated the mod to work with Minecraft 1.21

**Comment by FxMorin** [comment]
The mod will no longer be getting updates. Most issues were fixed by mojang.

**Comment by e-splat** [comment]
> The mod will no longer be getting updates. Most issues were fixed by mojang.

you said most, so for the issues still here update it for them

**Comment by ajaxnotmeta** [comment]
> The mod will no longer be getting updates. Most issues were fixed by mojang.

does world leaking thing still hapening or it was mostly fixed by mojang end?
if its fixed good then xD

**Comment by itsarian** [comment]
would be nice if the modrinth page was archived

**Comment by stema180** [comment]
> The mod will no longer be getting updates. Most issues were fixed by mojang.

well im having big memory leak issues, literally the game crashes like 3 hours after i open it saying i ran out of memory, and suggests i push it to over 10GB, which still does nothing, it just takes 4 hours instead

**Comment by Soabac** [comment]
> well im having big memory leak issues, literally the game crashes like 3 hours after i open it saying i ran out of memory, and suggests i push it to over 10GB, which still does nothing, it just takes 4 hours instead

look into it, might be an issue that wouldn't have been fixed with the mod, who knows. the mc modding discord community has channels for support you could ask over there, tell them your modlist, version and allat info. with modding it's always best to assume there is no magic fix it all mod
